services:
  app:
    image: ghcr.io/tahir-asadli/cpr-docker-image:latest
    # entrypoint: ['/var/www/html/entrypoint.sh']
    ports:
      - '8080:80'
    environment:
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - app_data:/var/www/html/storage/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    command: --sql-mode="NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./backup/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  app_data:
