<?php
return [
    "currencySymbol" => "₼",
    "freePlanDayLimit" => env("FREE_PLAN_DAY_LIMIT", 30),
    "freePlanPdfLimit" => env("FREE_PLAN_PDF_LIMIT", 5),
    "freePlanCVLimit" => env("FREE_PLAN_CV_LIMIT", 2),
    "freePlanPageLimit" => env("FREE_PLAN_PAGE_LIMIT", 4),
    'orderStatuses' => [
        'pending' => strtolower('Pending'),
        'completed' => strtolower('Completed'),
        'failed' => strtolower('Failed'),
    ],
    'subscriptionStatuses' => [
        'active' => strtolower('Active'),
        'cancelled' => strtolower('Deactivated - by user'),
        'deactivated' => strtolower('Deactivated'),
    ],
    'transactionStatuses' => [
        'failed' => strtolower('Failed'),
        'success' => strtolower('Success'),
    ],
    'socials' => [
        'Facebook' => '#1877F2',
        'YouTube' => '#ff0000',
        'Whatsapp' => '#075E54',
        'Instagram' => '#833AB4',
        'Snapchat' => '#000000',
        'Twitter' => '#08a0e9',
        'X' => '#000000',
        'LinkedIn' => '#0077B5',
        'Pinterest' => '#E60023',
        'Threads' => '#000000',
        'Telegram' => '#24A1DE',
        'Reddit' => '#FF4500',
        'Tumblr' => '#021A35',
        'Mastodon' => '#6364FF',
        'Twitch' => '#8956FB',
        'WeChat' => '#346b21',
        'Line' => '#21B94E',
        'Blogger' => '#FF5722',
        'Discord' => '#5865F2',
        'Yelp' => '#FF1A1A',
        'Medium' => '#000000',
        'Dribbble' => '#e74d89',
        'TikTok' => '#000000',
        'VK' => '#0077FF',
        'Flickr' => '#FF0084',
        'BlueSky' => '#0085ff',
        'Upwork' => '#6FDA44',
        'Fiverr' => '#1DBF73',
        'Guru' => '#005ea6',
        'Freelancer' => '#29b2fe',
        'Behance' => '#000000',
        'TopTal' => '#4b01da',
        'Skype' => '#00aff0',
        'GitHub' => '#000000',
        'GitLab' => '#ef5837',
        'StackOverflow' => '#e7700d',
        'DevTo' => '#000000',
        'WikiPedia' => '#636466',
        'Substack' => '#FF7731',
        'Shopify' => '#5E8E3E',
        'WordPress' => '#585C60',
        'Wix' => '#000000',
        'Link' => '#000000',
    ],
    'hobbies' => [
        'Drawing' => 'drawing',
        'Painting' => 'painting',
        'Photography' => 'photography',
        'Music' => 'music',
        'Crafting' => 'crafting',
        'Graphic Design' => 'graphic_design',
        'Hiking' => 'hiking',
        'Camping' => 'camping',
        'Cycling' => 'cycling',
        'Cycling2' => 'cycling2',
        'Swimming' => 'swimming',
        'Swimming2' => 'swimming2',
        'Swimming3' => 'swimming3',
        'Gardening' => 'gardening',
        'Fishing' => 'fishing',
        'Fishing2' => 'fishing2',
        'Fishing3' => 'fishing3',
        'Climbing' => 'climbing',
        'Running' => 'running',
        'Running2' => 'running2',
        'Martial Arts' => 'martial_arts',
        'Martial Arts2' => 'martial_arts2',
        'Martial Arts3' => 'martial_arts3',
        'Yoga' => 'yoga',
        'Meditation' => 'meditation',
        'Coding' => 'coding',
    ],
    'typography_widgets' => ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'space', 'ul', 'ol'],
    'has_alignments' => ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'space', 'ul', 'ol', 'image'],
    'has_uppercase' => ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'space', 'ul', 'ol'],
    'adminMail' => env('ADMIN_EMAIL', 'asadovtahir@gmail.com'),
    'seo_description' => strtolower('Online resume builder. Easily create your resume in just minutes with a template you love'),
    'seo_keywords' => strtolower('Online Resume, Online Resume, Resume preparation, Resume creation, Ready Resume forms, Pre-designed Resume templates, Resume examples, Sample Resumes, Create free PDF, Generate free PDF, Resume preparation service'),
    'seo_image' => env('APP_URL', 'http://localhost') . 'logo.svg',
    'logo' => env('APP_URL', 'http://localhost') . 'logo.svg',
    'logo-mobile' => env('APP_URL', 'http://localhost') . 'logo-mobile.svg',
    'logo_png' => env('APP_URL', 'http://localhost') . 'logo.png',
    'logo_square' => env('APP_URL', 'http://localhost') . 'logo-square.png',
    'download_all_rate_limiter_key' => 'download-all6942',
    'download_all_limit' => 1,
    'styles' => [
        'default' => [
            'slug' => 'default',
            'title' => 'Default',
            'color' => '#fff'
        ],
        'dark' => [
            'slug' => 'dark',
            'title' => 'Dark',
            'color' => '#626262'
        ],
        'blue' => [
            'slug' => 'blue',
            'title' => 'Blue',
            'color' => '#1c5dd9'
        ],
        'green' => [
            'slug' => 'green',
            'title' => 'Green',
            'color' => '#2f753d'
        ],
        'red' => [
            'slug' => 'red',
            'title' => 'Red',
            'color' => '#dd4220'
        ],
        'coffee' => [
            'slug' => 'coffee',
            'title' => 'Coffee',
            'color' => '#93562f'
        ],
        'cream' => [
            'slug' => 'cream',
            'title' => 'Cream',
            'color' => '#fceade'
        ],
        'tennis' => [
            'slug' => 'tennis',
            'title' => 'Tennis',
            'color' => '#466233'
        ],
        'pink' => [
            'slug' => 'pink',
            'title' => 'Pink',
            'color' => 'hotpink'
        ],
        'maroon' => [
            'slug' => 'maroon',
            'title' => 'Maroon',
            'color' => 'maroon'
        ],

    ],
    'geminiAPIKey' => env('GEMINI_API_TOKEN'),
    'geminiAPIEndpoint' => env('GEMINI_END_POINT'),
    'pdfParsePath' => env('PDF_PARSE_PATH'),
    'officeParsePath' => env('WORD_PARSE_PATH')
];
